In [1]:
import numpy as np

In [7]:
x=np.array([[1,2,3,4],[5,6,7,8],[8,9,0,1]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 9, 0, 1]])

In [8]:
x.ndim

2

In [9]:
x.shape

(3, 4)

In [10]:
y=np.array([[1,2],[3,4],[5,6],[7,8]])
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
y.shape

(4, 2)

In [12]:
y.ndim

2

In [13]:
y.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
lst=[1,2,3,4,5]

In [15]:
type(lst)

list

In [16]:
ar=np.array(lst)

In [17]:
type(ar)

numpy.ndarray

In [18]:
ar.min()

1

In [19]:
ar.max()

5

In [20]:
ar

array([1, 2, 3, 4, 5])

In [21]:
ar[0]

1

In [22]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [23]:
arr=np.array(l)

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

(3, 3)

In [26]:
ar.ndim

1

In [27]:
arr.ndim

2

In [28]:
arr.min()

1

In [29]:
arr.max()

9

In [47]:
l1=[[1,2,3],[1,2,36],[3,8,1],[9,10,11]]

In [48]:
a4=np.array(l1)

In [49]:
a4

array([[ 1,  2,  3],
       [ 1,  2, 36],
       [ 3,  8,  1],
       [ 9, 10, 11]])

In [50]:
a4.shape

(4, 3)

# Slicing

In [51]:
a4[0]

array([1, 2, 3])

In [52]:
a4[-1]

array([ 9, 10, 11])

In [53]:
a4[1:]

array([[ 1,  2, 36],
       [ 3,  8,  1],
       [ 9, 10, 11]])

In [54]:
a4[1:2]

array([[ 1,  2, 36]])

In [55]:
a4[1,2]

36

In [57]:
a4[2:,1:]

array([[ 8,  1],
       [10, 11]])

In [64]:
a4[0:2]=2

In [59]:
a4

array([[ 2,  2,  2],
       [ 2,  2,  2],
       [ 3,  8,  1],
       [ 9, 10, 11]])

In [62]:
a4[2,2]=2

In [63]:
a4

array([[ 2,  2,  2],
       [ 2,  2,  2],
       [ 3,  8,  2],
       [ 9, 10, 11]])

# inbuilt methods

# Functions to create numpy arrays

In [66]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [68]:
z1=np.zeros((3,3))
z1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
i=np.eye(5,5)        #identity matrix
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [75]:
np.linspace(0,10,20)     #20linearly spaced elements between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [78]:
np.random.rand(3)

array([0.02500064, 0.63516468, 0.82634939])

In [79]:
np.random.rand(3,5)

array([[0.84644867, 0.60389168, 0.69163684, 0.09742179, 0.40039264],
       [0.71075785, 0.77605689, 0.48003152, 0.45808178, 0.7961628 ],
       [0.2361309 , 0.00597504, 0.95056472, 0.29457545, 0.50968825]])

In [82]:
np.random.randint(3,10)

7

In [83]:
np.random.randint(3,100,56)

array([75, 25, 95, 44, 62,  5, 17, 90, 25, 38, 72, 65, 77, 99, 83, 55, 14,
       53, 19, 15, 43, 37,  3, 44, 34, 69, 59, 10, 40, 49, 28, 62, 26, 85,
       79, 53, 34, 76,  6, 13, 92, 64, 70, 67, 69, 13, 90, 72, 66, 18, 33,
       56, 50, 75, 51, 63])

In [84]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
a.shape

(20,)

In [86]:
a.ndim

1

In [87]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [88]:
s=np.arange(10).reshape(2,5)

In [89]:
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
x=np.random.randint(10,78,10).reshape(2,5)
x

array([[34, 66, 70, 42, 23],
       [16, 33, 30, 32, 48]])

In [94]:
x=np.random.rand(2,5).reshape(2,5)
x

array([[0.18113414, 0.81762118, 0.41269104, 0.79625762, 0.62754108],
       [0.10474218, 0.60155299, 0.11253551, 0.45347514, 0.50120427]])

In [96]:
x=np.linspace(10,70,10).reshape(2,5)
x

array([[10.        , 16.66666667, 23.33333333, 30.        , 36.66666667],
       [43.33333333, 50.        , 56.66666667, 63.33333333, 70.        ]])

In [97]:
s+x

array([[10.        , 17.66666667, 25.33333333, 33.        , 40.66666667],
       [48.33333333, 56.        , 63.66666667, 71.33333333, 79.        ]])

In [98]:
c=np.concatenate((s,x),axis=0)

In [99]:
c

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [10.        , 16.66666667, 23.33333333, 30.        , 36.66666667],
       [43.33333333, 50.        , 56.66666667, 63.33333333, 70.        ]])

In [100]:
np.delete(c,1,axis=0)  #del rows

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [10.        , 16.66666667, 23.33333333, 30.        , 36.66666667],
       [43.33333333, 50.        , 56.66666667, 63.33333333, 70.        ]])

In [101]:
np.delete(c,1,axis=1)  #del cols

array([[ 0.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  7.        ,  8.        ,  9.        ],
       [10.        , 23.33333333, 30.        , 36.66666667],
       [43.33333333, 56.66666667, 63.33333333, 70.        ]])

In [102]:
np.delete(c,[1,2],axis=1)

array([[ 0.        ,  3.        ,  4.        ],
       [ 5.        ,  8.        ,  9.        ],
       [10.        , 30.        , 36.66666667],
       [43.33333333, 63.33333333, 70.        ]])

In [103]:
a=np.arange(10)

In [104]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
r=a.ravel()
print(r)
f=a.flatten()
print(f)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [106]:
r[0]=10
r

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [107]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [108]:
f[5]=30
f

array([ 0,  1,  2,  3,  4, 30,  6,  7,  8,  9])

In [109]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [110]:
a+a

array([20,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
a*a

array([100,   1,   4,   9,  16,  25,  36,  49,  64,  81])

In [112]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
np.sqrt(a)

array([3.16227766, 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [115]:
np.exp(a)

array([2.20264658e+04, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [116]:
np.log(a)

array([2.30258509, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [117]:
np.max(a)

10

In [119]:
np.argmax(a)   #index of max num

0

In [120]:
np.argmin(a)

1